/*
 * This source file was generated by the Gradle 'init' task
 */
package io.shawlynot;

import io.shawlynot.client.KrakenClient;

import java.util.concurrent.ExecutionException;

public class App {

    public static void main(String[] args) throws ExecutionException, InterruptedException {
        try (var client = new KrakenClient()) {
            client.await();
        }
    }
}
