/*
 * This source file was generated by the Gradle 'init' task
 */
package io.shawlynot.marketdata;

import io.shawlynot.marketdata.client.KrakenClient;

import java.util.concurrent.ExecutionException;

public class App {

    public static void main(String[] args) throws ExecutionException, InterruptedException {
        try (var client = KrakenClient.subscribe().get()) {
            client.await();
        }
    }
}
